/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 bunny.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bunny.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh.geometry} material={materials.base} />
    </group>
  )
}

useGLTF.preload('/bunny.glb')
