name: release
on:
  push:
    branches:
      - 'main'

# Cancel any previous run (see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-job:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          brew install imagemagick jq fonttools
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - id: main
        run: |
          yarn install
          yarn build
          yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
